# Generated by Django 4.2 on 2023-04-13 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('tel_number', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=255)),
                ('priority', models.IntegerField(choices=[(1, 'Low'), (2, 'Medium'), (3, 'High')])),
                ('money_debt', models.DecimalField(decimal_places=2, max_digits=10)),
                ('type', models.CharField(choices=[('A', 'физлицо'), ('B', 'фирма'), ('C', 'исполнитель')], max_length=1)),
            ],
        ),
    ]
